/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of ApiResponse
 *
 * @constructor
 */
angular.module('SwaggerPetstoreLib')
    .factory('ApiResponse', ['BaseModel', ApiResponseModel]);

    function ApiResponseModel(BaseModel) {
        var ApiResponse = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.code = this.getValue(obj.code);
            this.type = this.getValue(obj.type);
            this.message = this.getValue(obj.message);
        };

        ApiResponse.prototype = new BaseModel();
        ApiResponse.prototype.constructor = ApiResponse;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        ApiResponse.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'code', realName: 'code' },
                { name: 'type', realName: 'type' },
                { name: 'message', realName: 'message' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        ApiResponse.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {int|null}
         */
        ApiResponse.prototype.getCode = function () {
            return this.code;
        };
    
        /**
         * Setter for Code
         * 
         * @param {int|null} value 
         */
        ApiResponse.prototype.setCode = function (value) {
            this.code = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ApiResponse.prototype.getType = function () {
            return this.type;
        };
    
        /**
         * Setter for Type
         * 
         * @param {string|null} value 
         */
        ApiResponse.prototype.setType = function (value) {
            this.type = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string|null}
         */
        ApiResponse.prototype.getMessage = function () {
            return this.message;
        };
    
        /**
         * Setter for Message
         * 
         * @param {string|null} value 
         */
        ApiResponse.prototype.setMessage = function (value) {
            this.message = value;
        };
    
        return ApiResponse;
    }

}(angular));
