/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('SwaggerPetstoreLib')
    .factory('StatusEnum', [StatusEnumModel]);

    function StatusEnumModel() {
        return {
            //TODO: Write general description for this element
            PLACED: 'placed',
    
            //TODO: Write general description for this element
            APPROVED: 'approved',
    
            //TODO: Write general description for this element
            DELIVERED: 'delivered'
        };
    }

}(angular));
