/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('SwaggerPetstoreLib')
    .factory('Status2Enum', [Status2EnumModel]);

    function Status2EnumModel() {
        return {
            //TODO: Write general description for this element
            AVAILABLE: 'available',
    
            //TODO: Write general description for this element
            PENDING: 'pending',
    
            //TODO: Write general description for this element
            SOLD: 'sold'
        };
    }

}(angular));
