/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('SwaggerPetstoreLib')
    .factory('Status1Enum', [Status1EnumModel]);

    function Status1EnumModel() {
        return {
            //TODO: Write general description for this element
            AVAILABLE: 'available',
    
            //TODO: Write general description for this element
            PENDING: 'pending',
    
            //TODO: Write general description for this element
            SOLD: 'sold'
        };
    }

}(angular));
