/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';
angular.module('SwaggerPetstoreLib')
    .factory('ModelFactory', ['Order', 'User', 'Category', 'Tag', 'Pet', 'ApiResponse', 'OAuthToken',ModelFactory]);

	/**
	 * Factory service to create instances of models and exception classes
	 */
    function ModelFactory(Order, User, Category, Tag, Pet, ApiResponse, OAuthToken) {

		var classMap = {
            Order: Order,
            User: User,
            Category: Category,
            Tag: Tag,
            Pet: Pet,
            ApiResponse: ApiResponse,
            OAuthToken: OAuthToken
		};

		return {
		    /**
		     * Creates instance of a model class
		     * @param  modelName  {string}  Name of class to instantiate
		     * @returns  {object} Instance of the model class
		     */
			getInstance: function(modelName) {
        		return new classMap[modelName]();
			}
		};
	}

}(angular));
