/**
 * SwaggerPetstoreLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

;(function (angular) {
'use strict';

angular.module('SwaggerPetstoreLib')
    .factory('Servers', [ServersModel]);

    function ServersModel() {
        return {
            //TODO: Write general description for this element
            SERVER_1: 'server1',
    
            //TODO: Write general description for this element
            SERVER_2: 'server2',
    
            //TODO: Write general description for this element
            AUTH_SERVER: 'auth server'
        };
    }

}(angular));
